"""A fresh real mailbox letter, followed by role-aware bell-turn evidence."""

import json
from pathlib import Path
import shlex
import sys
import time

from .conversation import bell_turn, messages
from .processes import ProcessError
from .protection import private_directory, write_private
from .scenes import transcript


def measure(runtime, pane, recipe, home, cwd, bell, seconds):
    initial = runtime.agent(pane)
    session = initial.get("agent_session") if initial else None
    file = transcript(home, recipe["kind"], session)
    if file is None:
        return {"outcome": "unknown", "reason": "no_supported_positive_native_session_reader"}
    if initial["agent_status"] == "blocked":
        return {"outcome": "unknown", "reason": "recipient_blocked"}
    offset = len(messages(file, recipe["kind"]))
    hidden = runtime.probe / ".letter-proof"
    private_directory(hidden)
    receipt = hidden / (recipe["id"] + ".json")
    helper = cwd / "queue-letter.py"
    # The marker is generated by the helper after its prompt was submitted.
    # The helper prints no marker or letter body, and the native write sandbox
    # forbids reading .letter-proof, including from a tool on the bell turn.
    program = f'''import json, os, pathlib, secrets, sys
sys.path.insert(0, {str(runtime.checkout / "scripts")!r})
from agent_live_check.processes import OwnedProcesses
marker = "LIVE_MAIL_" + secrets.token_hex(16)
with OwnedProcesses() as owner:
    code, out, err = owner.run([{str(runtime.hide)!r}, "request", "send", os.environ["HERDR_PANE_ID"], "--intent", "live-proof-" + secrets.token_hex(8), "--kind", "report", "--body", "Reply with this marker in your own assistant text: " + marker], env=dict(os.environ), check=False)
    answer = json.loads(out) if out else {{"ok": False}}
    if code or not answer.get("ok"):
        print("Letter could not be queued.")
        raise SystemExit(2)
    fd = os.open({str(receipt)!r}, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w") as stream:
        json.dump({{"marker": marker, "letter_id": answer["result"]["id"]}}, stream)
print("Letter queued. Reply READY without reading mail until a new bell turn.")
'''
    write_private(helper, program.encode())
    prompt = ("For this one delivery measurement, run " + shlex.quote(sys.executable) + " " + shlex.quote(str(helper)) +
              " once, then reply exactly READY. It sends a private test letter to this pane. "
              "Do not inspect the helper's data, read mail, use other tools, or change anything. "
              "If execution needs approval, leave the approval pending.")
    runtime.send(pane, prompt)
    deadline = time.monotonic() + seconds
    marker = letter_id = None
    sent = False
    while time.monotonic() < deadline:
        current = runtime.agent(pane)
        if not current or current.get("agent_session") != session:
            return {"outcome": "unknown", "reason": "recipient_identity_changed"}
        if receipt.exists() and marker is None:
            value = json.loads(receipt.read_text())
            marker, letter_id = value["marker"], value["letter_id"]
            write_private(runtime.run / (recipe["id"] + "-letter-receipt.json"), receipt.read_bytes())
        fresh = messages(file, recipe["kind"])[offset:]
        if marker and bell_turn(fresh, bell, marker):
            return {"outcome": "verified", "reason": "private_hided_letter_marker_in_bell_started_assistant_reply",
                    "letter_id": letter_id, "session_source": session["source"]}
        if current["agent_status"] == "blocked":
            return {"outcome": "unknown", "reason": "helper_or_inbox_needs_approval", "letter_id": letter_id}
        if marker and not sent and current["agent_status"] in ("idle", "done"):
            # If hided has already belled, do not type a second bell.
            if not any(role == "user" and (text == bell or text.startswith(bell + "\n")) for role, text in fresh):
                runtime.send(pane, bell)
            sent = True
        if runtime.owner.cancelled.wait(0.15):
            raise ProcessError("run_cancelled")
    return {"outcome": "unknown", "reason": "delivery_observation_timeout", "letter_id": letter_id}
