import Testing
@testable import HerdrMacOS

/// The reported defect was a chord the operator believed was bound and that
/// nothing claimed, so it fell through to the terminal and vanished. These
/// assert what the menu claims, which is the only thing that decides whether a
/// keypress reaches the shell at all.
@Suite("Shell menu shortcuts")
struct ShellMenuCommandTests {
    @Test func theRightPanelTogglesOnCommandShiftB() {
        #expect(ShellMenuCommand.toggleRightPanel.shortcut.canonical == "command+shift+b")
        #expect(ShellMenuCommand.toggleRightPanel.displayShortcut == "⇧⌘B")
    }

    @Test func theRetiredOptionChordIsClaimedByNothing() {
        let retired = PaneShortcut(key: "b", modifiers: [.command, .option])
        #expect(!ShellMenuCommand.allCases.contains { $0.shortcut == retired })
        #expect(!PaneCommand.allCases.contains { $0.defaultShortcut == retired })
    }

    @Test func recentNavigationAndDirectSelectionFollowThePublicContract() {
        #expect(ShellMenuCommand.recentTab.shortcut.canonical == "control+tab")
        #expect(ShellMenuCommand.previousRecentTab.shortcut.canonical == "control+shift+tab")
        #expect(ShellMenuCommand.recentProject.shortcut.canonical == "option+tab")
        #expect(ShellMenuCommand.previousRecentProject.shortcut.canonical == "option+shift+tab")
        for number in 1...9 {
            #expect(HideCommand.agent(number).shortcut(bindings: [:])?.canonical == "option+\(number)")
            #expect(HideCommand.tab(number).shortcut(bindings: [:])?.canonical == "command+\(number)")
        }
    }

    @Test func noTwoMenuCommandsClaimTheSameChord() {
        let chords = ShellMenuCommand.allCases.map(\.shortcut.canonical)
        #expect(Set(chords).count == chords.count)
    }

    /// The direct-select chords are generated by a loop rather than declared
    /// here, so they are the one set the uniqueness check above cannot see.
    @Test func noMenuCommandCollidesWithADirectSelectionChord() {
        let selectionChords = ShellMenuCommandTests.directSelectionChords
        for command in ShellMenuCommand.allCases {
            #expect(!selectionChords.contains(command.shortcut.canonical))
        }
    }

    /// ⌘n numbers the tabs and ⌥n numbers the agent rows, and the keycaps
    /// drawn on both surfaces claim exactly that. A chord catalogue that
    /// disagreed with the keycap would print a shortcut that does nothing.
    static let directSelectionChords: Set<String> = {
        let tabChords = (1...TabShortcutNumbering.capacity).map {
            PaneShortcut(key: "\($0)", modifiers: [.command]).canonical
        }
        let agentChords = (1...AgentShortcutNumbering.capacity).map {
            PaneShortcut(key: "\($0)", modifiers: [.option]).canonical
        }
        return Set(tabChords + agentChords)
    }()

    @Test func onlyRecentNavigationUsesNonCommandMenuChords() {
        for command in ShellMenuCommand.allCases {
            #expect(command.shortcut.modifiers.contains(.command) || command.shortcut.key == "tab")
        }
    }

    /// Menu chords and pane chords are declared in two separate catalogs and
    /// resolved by two different paths, so nothing but this check stops one
    /// from shadowing the other. `⌘0` next to the `⌘1`-`⌘9` tab chords is
    /// exactly the kind of neighbour that makes the gap worth holding open.
    @Test func noPaneCommandCollidesWithAMenuOrSelectionChord() {
        let menuChords = Set(ShellMenuCommand.allCases.map(\.shortcut.canonical))
        let selectionChords = ShellMenuCommandTests.directSelectionChords
        let paneChords = PaneCommand.allCases.map(\.defaultShortcut.canonical)
        #expect(Set(paneChords).count == paneChords.count)
        for chord in paneChords {
            #expect(!menuChords.contains(chord))
            #expect(!selectionChords.contains(chord))
        }
    }

    /// The three text-size commands are text size, not the layout zoom that
    /// `toggleZoom` already means. Naming them apart is the whole reason the
    /// two can coexist as pane commands.
    @Test func onlyTheTextSizeCommandsCarryAScaleDirection() {
        #expect(PaneCommand.increaseTextSize.textScaleDirection == .in)
        #expect(PaneCommand.decreaseTextSize.textScaleDirection == .out)
        #expect(PaneCommand.resetTextSize.textScaleDirection == .reset)
        #expect(PaneCommand.toggleZoom.textScaleDirection == nil)
        #expect(PaneCommand.closePane.textScaleDirection == nil)
        #expect(PaneCommand.splitRight.textScaleDirection == nil)
        #expect(PaneCommand.splitDown.textScaleDirection == nil)
    }
}
