import Testing
@testable import HerdrMacOS

/// The reported defect was a chord the operator believed was bound and that
/// nothing claimed, so it fell through to the terminal and vanished. These
/// assert what the menu claims, which is the only thing that decides whether a
/// keypress reaches the shell at all.
@Suite("Shell menu shortcuts")
struct ShellMenuCommandTests {
    @Test func theRightPanelTogglesOnCommandShiftB() {
        #expect(ShellMenuCommand.toggleRightPanel.shortcut.canonical == "command+shift+b")
        #expect(ShellMenuCommand.toggleRightPanel.displayShortcut == "⇧⌘B")
    }

    @Test func theRetiredOptionChordIsClaimedByNothing() {
        let retired = PaneShortcut(key: "b", modifiers: [.command, .option])
        #expect(!ShellMenuCommand.allCases.contains { $0.shortcut == retired })
        #expect(!PaneCommand.allCases.contains { $0.defaultShortcut == retired })
    }

    @Test func noTwoMenuCommandsClaimTheSameChord() {
        let chords = ShellMenuCommand.allCases.map(\.shortcut.canonical)
        #expect(Set(chords).count == chords.count)
    }

    /// The agent-selection chords are generated by a loop rather than declared
    /// here, so they are the one set the uniqueness check above cannot see.
    @Test func noMenuCommandCollidesWithAnAgentSelectionChord() {
        let agentChords = Set(
            (1...AgentShortcutNumbering.capacity).map { "command+\($0)" }
        )
        for command in ShellMenuCommand.allCases {
            #expect(!agentChords.contains(command.shortcut.canonical))
        }
    }

    @Test func everyMenuCommandRequiresCommand() {
        for command in ShellMenuCommand.allCases {
            #expect(command.shortcut.modifiers.contains(.command))
        }
    }
}
