import Testing
@testable import HerdrMacOS

/// The reported defect was a chord the operator believed was bound and that
/// nothing claimed, so it fell through to the terminal and vanished. These
/// assert what the menu claims, which is the only thing that decides whether a
/// keypress reaches the shell at all.
@Suite("Shell menu shortcuts")
struct ShellMenuCommandTests {
    @Test func theRightPanelTogglesOnCommandShiftB() {
        #expect(ShellMenuCommand.toggleRightPanel.shortcut.canonical == "command+shift+b")
        #expect(ShellMenuCommand.toggleRightPanel.displayShortcut == "⇧⌘B")
    }

    @Test func theRetiredOptionChordIsClaimedByNothing() {
        let retired = PaneShortcut(key: "b", modifiers: [.command, .option])
        #expect(!ShellMenuCommand.allCases.contains { $0.shortcut == retired })
        #expect(!PaneCommand.allCases.contains { $0.defaultShortcut == retired })
    }

    @Test func noTwoMenuCommandsClaimTheSameChord() {
        let chords = ShellMenuCommand.allCases.map(\.shortcut.canonical)
        #expect(Set(chords).count == chords.count)
    }

    /// The agent-selection chords are generated by a loop rather than declared
    /// here, so they are the one set the uniqueness check above cannot see.
    @Test func noMenuCommandCollidesWithAnAgentSelectionChord() {
        let agentChords = Set(
            (1...AgentShortcutNumbering.capacity).map { "command+\($0)" }
        )
        for command in ShellMenuCommand.allCases {
            #expect(!agentChords.contains(command.shortcut.canonical))
        }
    }

    @Test func everyMenuCommandRequiresCommand() {
        for command in ShellMenuCommand.allCases {
            #expect(command.shortcut.modifiers.contains(.command))
        }
    }

    /// Menu chords and pane chords are declared in two separate catalogs and
    /// resolved by two different paths, so nothing but this check stops one
    /// from shadowing the other. `⌘0` next to the `⌘1`-`⌘9` agent chords is
    /// exactly the kind of neighbour that makes the gap worth holding open.
    @Test func noPaneCommandCollidesWithAMenuOrAgentChord() {
        let menuChords = Set(ShellMenuCommand.allCases.map(\.shortcut.canonical))
        let agentChords = Set(
            (1...AgentShortcutNumbering.capacity).map { "command+\($0)" }
        )
        let paneChords = PaneCommand.allCases.map(\.defaultShortcut.canonical)
        #expect(Set(paneChords).count == paneChords.count)
        for chord in paneChords {
            #expect(!menuChords.contains(chord))
            #expect(!agentChords.contains(chord))
        }
    }

    /// The three text-size commands are text size, not the layout zoom that
    /// `toggleZoom` already means. Naming them apart is the whole reason the
    /// two can coexist as pane commands.
    @Test func onlyTheTextSizeCommandsCarryAScaleDirection() {
        #expect(PaneCommand.increaseTextSize.textScaleDirection == .in)
        #expect(PaneCommand.decreaseTextSize.textScaleDirection == .out)
        #expect(PaneCommand.resetTextSize.textScaleDirection == .reset)
        #expect(PaneCommand.toggleZoom.textScaleDirection == nil)
        #expect(PaneCommand.closePane.textScaleDirection == nil)
        #expect(PaneCommand.splitRight.textScaleDirection == nil)
        #expect(PaneCommand.splitDown.textScaleDirection == nil)
    }
}
