use super::*;
use Capability::{Available, Unavailable, Unconfirmed};

/// The supported order is also the stable Settings order.
pub const ADAPTERS: &[AgentAdapter] = &[
    AgentAdapter {
        key: AgentId::ClaudeCode,
        id: "claude-code",
        label: "Claude Code",
        picker_label: "Claude",
        sidebar_label: Some("Claude"),
        sidebar_mark: Some(SidebarMark::Claude),
        terminal_click: true,
        aliases: &["claude", "claude_code"],
        executables: &["claude"],
        skill_location: SkillLocation::Claude,
        skill_os: Os::ALL,
        hook: HookInstall::Runtime(HookDialect::ClaudeCode),
        herdr: HerdrIntegration {
            name: "claude",
            folder: &[".claude"],
        },
        default_on: true,
        prompt_hook: Some(HookDialect::ClaudeCode),
        spawn_guard: Some(HookDialect::ClaudeCode),
        subagent_counts: Some(HookDialect::ClaudeCode),
        memory: Some(HookDialect::ClaudeCode),
        bell: true,
        session: Some(SessionFormat::Claude),
        sleep: Some(LaunchDialect::Claude),
        fork: Some(LaunchDialect::Claude),
        resume: Some(LaunchDialect::Claude),
        conversation: Some(SessionFormat::Claude),
        titles: Some(SessionFormat::Claude),
        start: Some(LaunchDialect::Claude),
        find: Some(FindDialect::ClaudeTranscript),
        usage: Some(UsageDialect::Claude),
        doc_url: "https://code.claude.com/docs/en/skills",
        install_url: "https://code.claude.com/docs/en/setup",
        logo_id: "claude-code",
        factory: FactoryCapabilities {
            direct_ask: Available(DirectAsk {
                tools: &["AskUserQuestion", "ExitPlanMode"],
                denial: HookDialect::ClaudeCode,
            }),
            user_turn: Available(SessionFormat::Claude),
            turn_end_and_answer: Available(SessionFormat::Claude),
            startup_guidance: Available(HookInstall::Runtime(HookDialect::ClaudeCode)),
            resume: Available(LaunchDialect::Claude),
            next_prompt_letters: Available(HookDialect::ClaudeCode),
        },
    },
    AgentAdapter {
        key: AgentId::Codex,
        id: "codex",
        label: "Codex",
        picker_label: "Codex",
        sidebar_label: Some("Codex"),
        sidebar_mark: Some(SidebarMark::Codex),
        terminal_click: false,
        aliases: &[],
        executables: &["codex"],
        skill_location: SkillLocation::Shared,
        skill_os: Os::UNIX,
        hook: HookInstall::Runtime(HookDialect::Codex),
        herdr: HerdrIntegration {
            name: "codex",
            folder: &[".codex"],
        },
        default_on: true,
        prompt_hook: Some(HookDialect::Codex),
        spawn_guard: Some(HookDialect::Codex),
        subagent_counts: Some(HookDialect::Codex),
        memory: Some(HookDialect::Codex),
        bell: true,
        session: Some(SessionFormat::Codex),
        sleep: Some(LaunchDialect::Codex),
        fork: Some(LaunchDialect::Codex),
        resume: Some(LaunchDialect::Codex),
        conversation: Some(SessionFormat::Codex),
        titles: Some(SessionFormat::Codex),
        start: Some(LaunchDialect::Codex),
        find: Some(FindDialect::CodexTranscript),
        usage: Some(UsageDialect::Codex),
        doc_url: "https://learn.chatgpt.com/docs/build-skills",
        install_url: "https://learn.chatgpt.com/docs/codex/cli",
        logo_id: "codex",
        factory: FactoryCapabilities {
            direct_ask: Available(DirectAsk {
                tools: &["request_user_input"],
                denial: HookDialect::Codex,
            }),
            user_turn: Available(SessionFormat::Codex),
            turn_end_and_answer: Available(SessionFormat::Codex),
            startup_guidance: Available(HookInstall::Runtime(HookDialect::Codex)),
            resume: Available(LaunchDialect::Codex),
            next_prompt_letters: Available(HookDialect::Codex),
        },
    },
    AgentAdapter {
        key: AgentId::Grok,
        id: "grok",
        label: "Grok",
        picker_label: "Grok",
        sidebar_label: None,
        sidebar_mark: None,
        terminal_click: false,
        aliases: &[],
        executables: &["grok"],
        skill_location: SkillLocation::Shared,
        skill_os: Os::UNIX,
        hook: HookInstall::None,
        herdr: HerdrIntegration {
            name: "grok",
            folder: &[".grok"],
        },
        default_on: false,
        prompt_hook: None,
        spawn_guard: None,
        subagent_counts: None,
        memory: None,
        bell: false,
        session: None,
        sleep: None,
        fork: None,
        resume: None,
        conversation: None,
        titles: None,
        start: None,
        find: None,
        usage: None,
        doc_url: "https://docs.x.ai/build/features/skills-plugins-marketplaces",
        install_url: "https://github.com/xai-org/grok-build",
        logo_id: "grok",
        factory: FactoryCapabilities {
            direct_ask: Unconfirmed,
            user_turn: Unconfirmed,
            turn_end_and_answer: Unconfirmed,
            startup_guidance: Unavailable,
            resume: Unconfirmed,
            next_prompt_letters: Unavailable,
        },
    },
    AgentAdapter {
        key: AgentId::OpenCode,
        id: "opencode",
        label: "OpenCode",
        picker_label: "OpenCode",
        sidebar_label: Some("OpenCode"),
        sidebar_mark: None,
        terminal_click: false,
        aliases: &[],
        executables: &["opencode"],
        skill_location: SkillLocation::Shared,
        skill_os: Os::UNIX,
        hook: HookInstall::None,
        herdr: HerdrIntegration {
            name: "opencode",
            folder: &[".config", "opencode"],
        },
        default_on: false,
        prompt_hook: None,
        spawn_guard: None,
        subagent_counts: None,
        memory: None,
        bell: false,
        session: Some(SessionFormat::OpenCode),
        sleep: None,
        fork: None,
        resume: None,
        conversation: None,
        titles: Some(SessionFormat::OpenCode),
        start: None,
        find: None,
        usage: None,
        doc_url: "https://opencode.ai/docs/skills/",
        install_url: "https://opencode.ai/docs/",
        logo_id: "opencode",
        factory: FactoryCapabilities {
            direct_ask: Unconfirmed,
            user_turn: Unconfirmed,
            turn_end_and_answer: Unconfirmed,
            startup_guidance: Unavailable,
            resume: Unconfirmed,
            next_prompt_letters: Unavailable,
        },
    },
    AgentAdapter {
        key: AgentId::Pi,
        id: "pi",
        label: "Pi",
        picker_label: "Pi",
        sidebar_label: None,
        sidebar_mark: None,
        terminal_click: false,
        aliases: &[],
        executables: &["pi"],
        skill_location: SkillLocation::Shared,
        skill_os: Os::ALL,
        hook: HookInstall::None,
        herdr: HerdrIntegration {
            name: "pi",
            folder: &[".pi", "agent"],
        },
        default_on: false,
        prompt_hook: None,
        spawn_guard: None,
        subagent_counts: None,
        memory: None,
        bell: false,
        session: None,
        sleep: None,
        fork: None,
        resume: None,
        conversation: None,
        titles: None,
        start: None,
        find: None,
        usage: None,
        doc_url: "https://github.com/earendil-works/pi/blob/main/packages/coding-agent/docs/skills.md",
        install_url: "https://pi.dev/",
        logo_id: "pi",
        factory: FactoryCapabilities {
            direct_ask: Unconfirmed,
            user_turn: Unconfirmed,
            turn_end_and_answer: Unconfirmed,
            startup_guidance: Unavailable,
            resume: Unconfirmed,
            next_prompt_letters: Unavailable,
        },
    },
    AgentAdapter {
        key: AgentId::Omp,
        id: "omp",
        label: "omp",
        picker_label: "omp",
        sidebar_label: None,
        sidebar_mark: None,
        terminal_click: false,
        aliases: &[],
        executables: &["omp"],
        skill_location: SkillLocation::Shared,
        skill_os: Os::UNIX,
        hook: HookInstall::None,
        herdr: HerdrIntegration {
            name: "omp",
            folder: &[".omp", "agent"],
        },
        default_on: false,
        prompt_hook: None,
        spawn_guard: None,
        subagent_counts: None,
        memory: None,
        bell: false,
        session: None,
        sleep: None,
        fork: None,
        resume: None,
        conversation: None,
        titles: None,
        start: None,
        find: None,
        usage: None,
        doc_url: "https://omp.sh/docs/skills",
        install_url: "https://omp.sh/docs/quickstart",
        logo_id: "omp",
        factory: FactoryCapabilities {
            direct_ask: Unconfirmed,
            user_turn: Unconfirmed,
            turn_end_and_answer: Unconfirmed,
            startup_guidance: Unavailable,
            resume: Unconfirmed,
            next_prompt_letters: Unavailable,
        },
    },
    AgentAdapter {
        key: AgentId::Cursor,
        id: "cursor",
        label: "Cursor",
        picker_label: "Cursor",
        sidebar_label: None,
        sidebar_mark: None,
        terminal_click: false,
        aliases: &[],
        executables: &["cursor-agent"],
        skill_location: SkillLocation::Shared,
        skill_os: Os::UNIX,
        hook: HookInstall::Guidance(GuidanceDialect::Cursor),
        herdr: HerdrIntegration {
            name: "cursor",
            folder: &[".cursor"],
        },
        default_on: false,
        prompt_hook: None,
        spawn_guard: None,
        subagent_counts: None,
        memory: None,
        bell: false,
        session: None,
        sleep: None,
        fork: None,
        resume: None,
        conversation: None,
        titles: None,
        start: None,
        find: None,
        usage: None,
        doc_url: "https://cursor.com/docs/context/skills",
        install_url: "https://cursor.com/docs/cli/installation",
        logo_id: "cursor",
        factory: FactoryCapabilities {
            direct_ask: Unconfirmed,
            user_turn: Unconfirmed,
            turn_end_and_answer: Unconfirmed,
            startup_guidance: Available(HookInstall::Guidance(GuidanceDialect::Cursor)),
            resume: Unconfirmed,
            next_prompt_letters: Unavailable,
        },
    },
];
