"""The attribution gate must reject a byline and accept naming the tools.

The gate exists because commit and pull request text must read as project work.
It grew a second requirement the day a change's whole subject was one of the
integrated CLIs: text that cannot name them cannot describe that change. These
tests hold both ends, so neither is loosened by accident.
"""
import importlib.util
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SPEC = importlib.util.spec_from_file_location(
    'check_no_attribution', ROOT / 'scripts' / 'check-no-attribution.py')
CHECK = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(CHECK)


class AttributionIsRejected(unittest.TestCase):
    def test_a_trailer_or_a_credit_phrase_fails(self):
        for text in [
            'Co-authored-by: Claude <noreply@anthropic.com>',
            'Add the router\n\nGenerated by Claude Code',
            'Fix the parser, authored by Codex',
            'co-authored-by: someone',
        ]:
            with self.subTest(text=text):
                self.assertIsNotNone(CHECK.offence(text), text)

    def test_quoting_a_credit_phrase_does_not_excuse_it(self):
        self.assertIsNotNone(CHECK.offence('Add the router\n\n`Generated by Claude`'))
        self.assertIsNotNone(CHECK.offence('```\nCo-authored-by: Claude\n```'))

    def test_a_credit_verb_fails_whichever_preposition_follows_it(self):
        """`by` was the only one checked, so `with` and `using` walked past it."""
        for text in [
            'Co-developed with Claude Code',
            'Built using Codex CLI',
            'Rewrite the router, implemented with Claude Code',
            'Assisted by Codex CLI',
            'Produced using Claude Code',
        ]:
            with self.subTest(text=text):
                self.assertIsNotNone(CHECK.offence(text), text)

    def test_a_bare_tool_name_in_prose_reads_as_a_byline(self):
        for text in [
            'Claude wrote the backend',
            'Rewrite the provider with Codex',
            'Ask Anthropic for the schema',
            'Use opus for the summaries',
        ]:
            with self.subTest(text=text):
                self.assertIsNotNone(CHECK.offence(text), text)


class NamingTheToolIsAllowed(unittest.TestCase):
    def test_a_quoted_command_is_a_citation(self):
        for text in [
            'Drive `claude -p --output-format json` once per request',
            'Read availability from `claude auth status --json`',
            'Start `codex app-server --listen stdio://`',
            'Measured on `claude` 2.1.267',
            'The frame is\n\n```\n{"subtype": "success"}\n```\nfrom `claude -p`',
        ]:
            with self.subTest(text=text):
                self.assertIsNone(CHECK.offence(text), text)

    def test_a_product_name_in_full_is_a_subject(self):
        for text in [
            'Drive Claude Code print mode as a background AI provider',
            'The Codex CLI and Claude Code are the two providers',
            'Measured on codex-cli 0.154.0',
        ]:
            with self.subTest(text=text):
                self.assertIsNone(CHECK.offence(text), text)

    def test_a_path_or_an_identifier_is_not_a_byline(self):
        for text in [
            'Keep `.claude/agents/` committed',
            'Replace ClaudeInteractiveBackend with ClaudeCliBackend',
            'Export claude::ClaudeConfig from the crate root',
            'Update docs/AI_PROVIDERS.md and .claude/settings.json',
        ]:
            with self.subTest(text=text):
                self.assertIsNone(CHECK.offence(text), text)

    def test_ordinary_project_text_passes(self):
        self.assertIsNone(CHECK.offence('Fix the tab reorder refusal in a split checkout'))


if __name__ == '__main__':
    unittest.main()
