#!/usr/bin/env python3
"""Reject attribution in delivery metadata and the prepared PR body."""
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent

def git(*args):
    return subprocess.check_output(['git', *args], cwd=ROOT, text=True)

body = ROOT / 'agents/runs/herdr-typed-contract/pr-body.md'
if not body.is_file():
    raise SystemExit('Prepare agents/runs/herdr-typed-contract/pr-body.md before checking delivery metadata')
texts = {
    'branch': git('branch', '--show-current'),
    'commits': git('log', '--format=%B', 'origin/main..HEAD'),
    'PR body': body.read_text(),
}
forbidden = re.compile(r'co-authored-by:|generated by|authored by|\b(?:codex|chatgpt|openai|anthropic|claude|gpt-\d|astra|sonnet|opus)\b', re.I)
for name, text in texts.items():
    if forbidden.search(text):
        raise SystemExit(f'Attribution found in {name}')
print('Branch, run commits and prepared PR body contain no attribution')
