#!/usr/bin/env python3
"""Reject AI tooling attribution in the branch name, commits and PR body.

CONTRIBUTING.md states the policy; this is its check. It was written against
one run's prepared body and only ever ran for that run, so the PR body is now
an argument and the commit range has a default any branch can use.
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The tool names are matched as words, never as part of a path: this
# repository tracks `.claude/agents/`, and a commit that names that directory
# is describing a file, not crediting a tool.
FORBIDDEN = re.compile(
    r'co-authored-by:|generated by|authored by|'
    r'(?<![./\w-])(?:codex|chatgpt|openai|anthropic|claude|gpt-\d|sonnet|opus)\b',
    re.IGNORECASE,
)


def git(*args: str) -> str:
    return subprocess.check_output(['git', *args], cwd=ROOT, text=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--range', default='origin/main..HEAD',
                        help='commit range to read (default: origin/main..HEAD)')
    parser.add_argument('--pr-body', type=Path,
                        help='path to the prepared pull request body, when one exists')
    arguments = parser.parse_args()

    texts = {
        'branch': git('branch', '--show-current'),
        f'commits in {arguments.range}': git('log', '--format=%B', arguments.range),
    }
    if arguments.pr_body is not None:
        if not arguments.pr_body.is_file():
            print(f'error: no pull request body at {arguments.pr_body}', file=sys.stderr)
            return 1
        texts[str(arguments.pr_body)] = arguments.pr_body.read_text()

    failed = False
    for name, text in texts.items():
        found = FORBIDDEN.search(text)
        if found:
            print(f'error: attribution "{found.group(0)}" found in {name}', file=sys.stderr)
            failed = True
    if failed:
        return 1
    print('No attribution in: ' + ', '.join(texts))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
