/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        sidebar: "var(--color-sidebar)",
        panel: "var(--color-panel)",
        elevated: "var(--color-elevated)",
        balloon: "var(--color-balloon)",
        divider: "var(--color-divider)",
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        muted: "var(--color-muted)",
        accent: "var(--color-accent)",
        danger: "var(--color-danger)",
        warning: "var(--color-warning)",
        success: "var(--color-success)",
        "agent-working": "var(--color-agent-working)",
        "pr-open": "var(--color-pr-open)",
        "pr-merged": "var(--color-pr-merged)",
        "pr-closed": "var(--color-pr-closed)",
        "pr-draft": "var(--color-pr-draft)",
        "file-neutral": "var(--color-file-neutral)",
        "file-document": "var(--color-file-document)",
        "file-blue": "var(--color-file-blue)",
        "file-green": "var(--color-file-green)",
        "file-orange": "var(--color-file-orange)",
        "file-yellow": "var(--color-file-yellow)",
        "file-purple": "var(--color-file-purple)",
      },
      spacing: {
        none: "var(--spacing-none)",
        xxs: "var(--spacing-xxs)",
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
      },
      fontSize: {
        micro: "var(--text-micro)",
        caption: "var(--text-caption)",
        body: "var(--text-body)",
        subhead: "var(--text-subhead)",
        title: "var(--text-title)",
      },
    },
  },
  plugins: [],
};
